### ISSUE TITLE
Fails with Config::Model 2.115

### ISSUE THREAD

**Issue by andk** [dod38fr/cme-perl#3]
As per subject.

Sample fail report: http://www.cpantesters.org/cpan/report/90133721

I get the same result on my smokers. Downgrading to DDUMONT/Config-Model-2.114.tar.gz does as a workaround to restore all tests passing.

**Comment by dod38fr** [comment]
I'm very sorry about the delay in replying to this issue. This report went under my radar.

This issue was fixed with Config::Model 2.116 released on 15 dec.

Thanks for the report.

Dod
